# fly.toml app configuration file generated for react-flow-api on 2024-05-08T22:40:55+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'react-flow-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
